"model":
  "type": "DFNet"
  "params":
    "in_channels": 1
    "hidden_channels": 64
    "L": 5
    "k": 12

"inference":
  "checkpoint_path": "/opt/data/private/TransCG/stats/train-realsense-syn/checkpoint.tar"
  "image_size": !!python/tuple [640, 480]
  "cuda_id": 0
  "depth_min": 0.3
  "depth_max": 1.0
  "depth_norm": 1.0
